language: python
python: "3.6"
os: linux
dist: xenial
addons:
  apt:
    packages:
      # Required packages to run the benchmark and collect results
      - valgrind
      - cloc

# Modify the script lines to compile and run your program. The output binary needs to be called `triplet_challenge`
script:
  - python ./src/triplet_challenge.py ./pg2009.txt

# Do not change the `after_script` lines since they are used to collect results to compare with other implementations
after_script:
  - wget https://github.com/sharkdp/hyperfine/releases/download/v1.3.0/hyperfine_1.3.0_amd64.deb && sudo dpkg -i hyperfine_1.3.0_amd64.deb
  - lscpu
  - cloc src
  - python ./src/triplet_challenge.py ./pg2009.txt
  - hyperfine -w 3 -m 10 "python ./src/triplet_challenge.py ./pg2009.txt"
  - valgrind --tool=massif --time-unit=B --massif-out-file=valgrind.out python ./src/triplet_challenge.py ./pg2009.txt
  - ms_print valgrind.out